import { useState } from 'react';
import { Link } from 'react-router-dom';
import { mealPlanDays, getRecipe } from '../data/recipes.js';
import { RecipeImage } from '../components/RecipeCard.jsx';
import Icon from '../components/Icon.jsx';

export default function MealPlans() {
  const [length, setLength] = useState(3);
  return <div className="container page-content"><header className="page-heading"><p className="eyebrow">FIND YOUR EVERYDAY RHYTHM</p><h1 tabIndex={-1}>A little plan.<br /><em>A lighter week.</em></h1><p>Simple meal ideas that work together, with familiar ingredients along the way.</p></header><section className="plan-intro"><div><h2>Start small. Make it yours.</h2><p>Choose a few days of inspiration or see the whole week. Swap meals freely to suit your appetite, preferences, and schedule.</p></div><fieldset className="segmented-control"><legend className="sr-only">Meal plan length</legend>{[3, 7].map(days => <label key={days} className={length === days ? 'selected' : ''}><input type="radio" name="plan-length" value={days} checked={length === days} onChange={() => setLength(days)} />{days}-day plan</label>)}</fieldset></section><p className="plan-result" role="status" aria-live="polite">Showing {length} days of meal inspiration</p><div className="plan-days">{mealPlanDays.slice(0, length).map((day, index) => <section className="plan-day" key={day.day}><div className="day-label"><span>DAY {String(index + 1).padStart(2, '0')}</span><h2>{day.day}</h2></div><div className="day-meals">{['breakfast', 'lunch', 'dinner'].map(meal => { const recipe = getRecipe(day[meal]); return <Link key={meal} to={`/recipes/${recipe.id}`} className="plan-meal"><RecipeImage recipe={recipe} sizes="120px" /><div><span className="eyebrow">{meal.toUpperCase()}</span><h3>{recipe.title}</h3><span className="meal-time"><Icon name="clock" size={14} />{recipe.time} min</span></div><Icon name="chevron" size={17} /></Link>; })}</div></section>)}</div><aside className="plan-footnote"><Icon name="bowl" size={30} /><div><h2>Inspiration, with room for real life.</h2><p>These are sample menus, not personalized nutrition plans. Add snacks, sides, and portions that suit you. Check each recipe’s ingredients before shopping.</p></div></aside></div>;
}
