import { Link } from 'react-router-dom';
import { RecipeImage } from '../components/RecipeCard.jsx';
import { getRecipe } from '../data/recipes.js';
import Icon from '../components/Icon.jsx';

const principles = [
  ['01', 'Make room for variety.', 'Fruit and vegetables bring different flavors, textures, and nutrients. Fresh, frozen, and canned options can all have a place.', 'leaf'],
  ['02', 'Give your meal a base.', 'Rice, potatoes, bread, and pasta help make a meal satisfying. Try wholegrain or higher-fiber versions when they work for you.', 'bowl'],
  ['03', 'Mix up your protein.', 'Beans, lentils, fish, eggs, and meat offer different ways to build a meal. Dairy or fortified alternatives can also fit into your day.', 'sun'],
];
export default function Nutrition() {
  return <div className="container page-content"><header className="nutrition-hero"><div><p className="eyebrow">THE EVERYDAY BASICS</p><h1 tabIndex={-1}>Good habits.<br /><em>Small beginnings.</em></h1><p className="detail-description">A little food knowledge can make everyday choices feel easier. Start with variety, flexibility, and meals you enjoy.</p></div><RecipeImage recipe={getRecipe('yogurt-fruit')} priority className="nutrition-image" sizes="(max-width: 899px) 100vw, 40vw" /></header><section className="nutrition-principles" aria-label="Everyday food principles">{principles.map(([number, title, text, icon]) => <article key={number}><div className="principle-top"><span>{number}</span><Icon name={icon} size={28} /></div><h2>{title}</h2><p>{text}</p></article>)}</section><p className="source-note">These general principles draw on the <a href="https://www.nhs.uk/live-well/eat-well/food-guidelines-and-food-labels/the-eatwell-guide/" target="_blank" rel="noreferrer">NHS Eatwell Guide</a>. Balance can happen across a day or week; every meal does not need to look the same.</p><section className="nutrition-tips section"><div><p className="eyebrow">MAKE IT WORK FOR YOUR KITCHEN</p><h2>Small swaps.<br />Fresh possibilities.</h2><p>Start with the ingredients you already like.</p><Link className="text-link" to="/recipes?diet=Vegetarian">Explore plant-based ideas <Icon name="arrow" size={18} /></Link></div><div className="swap-list"><details open><summary>Out of one ingredient?</summary><p>Try chickpeas instead of black beans in a bowl, or spinach instead of arugula. Flavors and cooking times will change, so taste and adjust as you go.</p></details><details><summary>Cooking for one?</summary><p>Look at the servings before you start. Halve the ingredients for a smaller batch, or plan another meal around the extra vegetables.</p></details><details><summary>Need a simpler week?</summary><p>Pick recipes with overlapping ingredients. The same bag of greens can go into toast, a grain bowl, and a side salad.</p></details><details><summary>Keeping food safe?</summary><p>Use a thermometer to check chicken reaches 165°F (74°C) and fish reaches 145°F (63°C). Cook eggs until the whites and yolks are firm. Follow <a href="https://www.foodsafety.gov/food-safety-charts/safe-minimum-internal-temperatures" target="_blank" rel="noreferrer">FoodSafety.gov guidance</a> for the food you are preparing.</p></details></div></section><aside className="education-note"><strong>A note on individual needs</strong><p>This is general food education, not personalized dietary advice. Portions and ingredients should fit your own needs. A registered dietitian can help with specific medical or dietary requirements.</p></aside></div>;
}
